#!/bin/bash   

# for cmsimde   _site no need to get submodule
# Update Git submodules
#git submodule update --init
   
# Install Python packages using pip
pip insta   ll flask flask_cors bs4 lxml pelican markdown gevent

# Optionally, you can add more commands or customizations here.
